const data = {
    products: [
      {
        _id: '1',
        name: 'Masala Dosa',
        category: 'Food',
        image: '/images/p1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Food',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality Food',
      },
      {
        _id: '2',
        name: 'Butter chicken',
        category: 'Dish',
        image: '/images/p7.jpg',
        price: 100,
        countInStock: 20,
        brand: 'kadhi',
        rating: 4.0,
        numReviews: 10,
        description: 'Punjabi, buttery and chicken--thats just the combo you need every day',
      },
      {
        _id: '3',
        name: 'Goan coconut crab curry',
        category: 'Dish',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Goan',
        rating: 4.8,
        numReviews: 17,
        description: 'This Goan seafood dish has some Portuguese influences, and is a must-have.',
      },
      {
        _id: '4',
        name: 'Chicken Chettinad',
        category: 'Dish',
        image: '/images/p9.jpg',
        price: 78,
        countInStock: 15,
        brand: 'Bhature',
        rating: 4.5,
        numReviews: 14,
        description: 'Chettinad spices can make the world a better place, especially when cooked with chicken'
      },

      {
        _id: '5',
        name: 'Kakori kebab',
        category: 'Dish',
        image: '/images/p5.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Kebab',
        rating: 4.5,
        numReviews: 10,
        description: 'The king of all seekh kebabs in India, Kakori kebabs are best paired with naans and lachcha paranthas.',
      },
      {
        _id: '6',
        name: 'Paturi',
        category: 'Dish',
        image: '/images/p6.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Paturi',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality dish',
      },
    ],
  };
  export default data;